name: ChestCleaner
version: 1.8.A1
author: Tom2208
api-version: "1.15"

main: chestcleaner.main.ChestCleaner

commands:
  cleaninventory:
    description: Cleans an inventory of a block.
    usage: /<command> <x> <y> <z>
    aliases: [cleaninv, cinv]
  cooldown:
    description: Configures the cooldown time of the sorting.
    usage: /<command> <setActive/setCooldown>
    aliases: cd
  cleaningitem:
    description: Configuration of the cleaningitem.
    usage: /<command> <get/give/rename/setActive/setDurabilityLoss/setEventDetectionMode/setItem/setLore>
    aliases: ci
  blacklist:
    description: Avoiding items to get stacked while sorting.
    usage: /<command> <sorting/inventories> <list/clear/addMaterial/removeMaterial>
    aliases: bl
  sortingconfig:
    description: Configuration of the sorting algorithm.
    usage: /<command> <pattern/evaluator/setautosort/adminconfig>
    aliases: [sconfig, sc]
